---
fixtures:
  repositories:
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup.git
    concat: https://github.com/simp/puppetlabs-concat.git
    simplib: https://github.com/simp/pupmod-simp-simplib.git
    sshkeys_core:  https://github.com/simp/pupmod-puppetlabs-sshkeys_core.git
    stdlib: https://github.com/simp/puppetlabs-stdlib.git
  symlinks:
    oath: "#{source_dir}"
